chore: update docusaurus to 2.0.0-rc.1
easyops-cn/docusaurus-search-local pull request #226
Opened 2022-07-18 15:57 UTC by utybo

I believe there are other issues related 2.0.0-rc.1, but at least it compiles with this PR! 🚀

Edit: I've added a fix for a problem I encountered while trying to use the new version with a website that does *not* use versions. The fix is a complete hack but I'm not aware of any way of making this better. Feel free to edit my PR if you have a better solution for this.

2022-07-18 17:33 UTC, utybo commented
There are still issues when not using versions, I'll probably use the same hack everywhere applicable.

2022-07-18 20:58 UTC, utybo commented
*In case people are interested, I have published my fixes as `@utybo/docusaurus-search-local` on [NPM](https://www.npmjs.com/package/@utybo/docusaurus-search-local). I'm currently using it to check that nothing else is broken on several of our (non-public) Docusaurus sites.*

2022-07-19 01:13 UTC, weareoutman requested changes

2022-07-19 01:13 UTC, weareoutman commented on docusaurus-search-local/package.json
> +  "version": "0.30.0",
The version will be increased automatically, so we should leave as it is

```suggestion
  "version": "0.29.0",
```

2022-07-19 01:13 UTC, weareoutman commented on docusaurus-search-local/tsconfig.json
> +    "module": "Node16",
👍 Thanks, I tried upgrade docusaurus to rc.1, but failed, I believe this is the magic here :)

2022-07-19 01:18 UTC, merged

2022-07-19 01:25 UTC, weareoutman commented
Thanks! Released in v0.29.1

2022-07-19 13:03 UTC, utybo commented
Thank you very much for the fast merge and release! 🚀